export const waterproofs = [
  {
    id: 1,
    name: "Waterproof Jacket 1",
    imageSrc: "/jacket1.jpg",
    imageAlt: "Waterproof jacket in blue.",
    description: "A high-quality waterproof jacket for all weather conditions.",
    options: "Available in sizes S, M, L, XL",
    price: "£120.00",
  },
  {
    id: 2,
    name: "Waterproof jacket 2",
    imageSrc: "/jacket2.jpg",
    imageAlt: "Waterproof pants in black.",
    description: "Durable waterproof pants for outdoor adventures.",
    options: "Available in sizes S, M, L, XL",
    price: "£90.00",
  },
  {
    id: 3,
    name: "Waterproof jacket3",
    imageSrc: "/jacket3.jpg",
    imageAlt: "Waterproof boots in brown.",
    description: "Comfortable waterproof boots for hiking and trekking.",
    options: "Available in sizes 7, 8, 9, 10, 11",
    price: "£150.00",
  },
  {
    id: 4,
    name: "Waterproof jacket 4",
    imageSrc: "/jacket4.jpg",
    imageAlt: "Waterproof gloves in black.",
    description: "Warm waterproof gloves for cold weather.",
    options: "Available in sizes S, M, L",
    price: "£40.00",
  },
  {
    id: 5,
    name: "Waterproof jacket 5",
    imageSrc: "/jacket5.jpg",
    imageAlt: "Waterproof hat in grey.",
    description: "Stylish waterproof hat for rainy days.",
    options: "One size fits all",
    price: "£30.00",
  },
  {
    id: 6,
    name: "Waterproof jacket 6",
    imageSrc: "/jacket1.jpg",
    imageAlt: "Waterproof backpack in green.",
    description: "Spacious waterproof backpack for travel.",
    options: "Available in various colors",
    price: "£80.00",
  },
];

export const windproofs = [
  {
    id: 11,
    name: "Windproof Jacket 1",
    imageSrc: "/jacket1.jpg",
    imageAlt: "windproof jacket in blue.",
    description: "A high-quality windproof jacket for all weather conditions.",
    options: "Available in sizes S, M, L, XL",
    price: "£120.00",
  },
  {
    id: 12,
    name: "Windproof jacket 2",
    imageSrc: "/jacket2.jpg",
    imageAlt: "windproof pants in black.",
    description: "Durable windproof pants for outdoor adventures.",
    options: "Available in sizes S, M, L, XL",
    price: "£90.00",
  },
];